baseURL = "https://marcospredebon.github.io/Siteweb/"
languageCode = "pt-br"
title = "Tecnologia e Criatividade"
enableGitInfo = false
canonifyURLs = false
relativeURLs = false

[params]
  description = "Referências de Tecnologia (Marcos Predebon) e o legado do Professor José Predebon"

[markup.goldmark.renderer]
  unsafe = true

[pagination]
  pagerSize = 50

[menu]
  [[menu.main]]
    name = "Tecnologia"
    url = "/tecnologia/"
    weight = 1

  [[menu.main]]
    name = "Criatividade"
    url = "/criatividade/"
    weight = 2
